default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DEPLOY_MANAGER_DATABASE_USERNAME'] %>
  password: <%= ENV['DEPLOY_MANAGER_DATABASE_PASSWORD'] %>
  host: <%= ENV['DEPLOY_MANAGER_DATABASE_HOST'] %>
  port: <%= ENV['DEPLOY_MANAGER_DATABASE_PORT'] %>

development:
  <<: *default
  database: deploy_manager_development
  username: <%= ENV['DEPLOY_MANAGER_DATABASE_USERNAME'] %>
  password: <%= ENV['DEPLOY_MANAGER_DATABASE_PASSWORD'] %>
  host: <%= ENV['DEPLOY_MANAGER_DATABASE_HOST'] %>
  port: <%= ENV['DEPLOY_MANAGER_DATABASE_PORT'] %>

test:
  <<: *default
  database: deploy_manager_test

production:
  <<: *default
  database: deploy_manager_production
  username: <%= ENV['DEPLOY_MANAGER_DATABASE_USERNAME'] %>
  password: <%= ENV['DEPLOY_MANAGER_DATABASE_PASSWORD'] %>
  host: <%= ENV['DEPLOY_MANAGER_DATABASE_HOST'] %>
  port: <%= ENV['DEPLOY_MANAGER_DATABASE_PORT'] %>

